=== 0x90v1/BlurRebuilt/Blur1PC/code/tools/c_sharp/applications/executer/test_data/executer.dtd
<!ELEMENT root (config, servers, actions, processes?, tree_icon_folder?, types)>
<!ATTLIST root version				CDATA #REQUIRED >

<!ELEMENT tree_icon_folder EMPTY>
<!ATTLIST tree_icon_folder name CDATA #REQUIRED >

<!ELEMENT config EMPTY>
<!ATTLIST config farm_temp_folder				CDATA #REQUIRED >
<!ATTLIST config owner_product_name			CDATA #REQUIRED >

<!ELEMENT servers	(server_definition*)>

<!ELEMENT server_definition EMPTY>
<!ATTLIST server_definition name						CDATA #REQUIRED >
<!ATTLIST server_definition tcp_port				CDATA #REQUIRED >
<!ATTLIST server_definition udp_port				CDATA #IMPLIED >
<!ATTLIST server_definition local_name			CDATA #REQUIRED >
<!ATTLIST server_definition location				CDATA #REQUIRED >
<!ATTLIST server_definition startup_command	CDATA #IMPLIED >
<!ATTLIST server_definition kill_on_exit		(true|false|yes|no) "false" >

<!ELEMENT actions	(action+)>

<!ELEMENT action	(server_list?)>
<!ATTLIST action name CDATA #REQUIRED >
<!ATTLIST action command_line CDATA #REQUIRED >
<!ATTLIST action working_directory CDATA #IMPLIED >
<!ATTLIST action arguments CDATA #IMPLIED >
<!ATTLIST action include_child_data (true|false|yes|no) "false" >
<!ATTLIST action include_parent_data (true|false|yes|no) "false" >
<!ATTLIST action hide_process (true|false|yes|no) "false" >
<!ATTLIST action include_xml_data_file CDATA #IMPLIED >

<!ELEMENT server_list	(server*)>

<!ELEMENT server EMPTY>
<!ATTLIST server local_name CDATA #REQUIRED >

<!ELEMENT processes	(process*)>

<!ELEMENT process	EMPTY>
<!ATTLIST process name CDATA #REQUIRED >
<!ATTLIST process local_name CDATA #REQUIRED >

<!ELEMENT types	(type*)>

<!ELEMENT type	(task_list?, inheritable_types?, sub_menu_template?)>
<!ATTLIST type name CDATA #REQUIRED icon1 CDATA #IMPLIED icon2 CDATA #IMPLIED >

<!ELEMENT task_list (task*)>

<!ELEMENT task EMPTY>
<!ATTLIST task name CDATA #REQUIRED display_name CDATA #REQUIRED action_name CDATA #REQUIRED process_recursively (true|false|yes|no|ask) "ask">
<!ATTLIST task farm_comment CDATA #IMPLIED >

<!ELEMENT inheritable_types (inheritable_type*)>

<!ELEMENT inheritable_type EMPTY>
<!ATTLIST inheritable_type name CDATA #REQUIRED>

<!ELEMENT sub_menu_template (menu_system?)>

<!ELEMENT menu_system (enums?, container)>

<!ELEMENT enums (enum*)>

<!ELEMENT enum (#PCDATA)>
<!ATTLIST enum name CDATA #REQUIRED>

<!ELEMENT container (container*)>
<!ATTLIST container name CDATA #REQUIRED display_name CDATA #IMPLIED type CDATA #REQUIRED >
<!ATTLIST container pre_format CDATA #IMPLIED >
<!ATTLIST container post_format CDATA #IMPLIED >
<!ATTLIST container default CDATA #IMPLIED >
<!ATTLIST container save (true|false) "true">
<!ATTLIST container bitmap CDATA #IMPLIED >
<!ATTLIST container values CDATA #IMPLIED >
<!ATTLIST container filepicker_filter CDATA #IMPLIED >
<!-- Filemask filter for filepicker type. -->
<!ATTLIST container filepicker_share_name CDATA #IMPLIED >
<!ATTLIST container force_local_network_path (true|false) #IMPLIED>
<!ATTLIST container force_file_exists (true|false) #IMPLIED>
<!ATTLIST container force_path_exists (true|false) #IMPLIED>
<!ATTLIST container command CDATA #IMPLIED >
<!ATTLIST container working_directory CDATA #IMPLIED >
<!ATTLIST container always_enabled CDATA #IMPLIED >
<!ATTLIST container min CDATA #IMPLIED >
<!ATTLIST container max CDATA #IMPLIED >
<!ATTLIST container width CDATA #IMPLIED >
<!ATTLIST container depends_on CDATA #IMPLIED >
<!ATTLIST container style CDATA #IMPLIED >

<!--	<!ATTLIST container filepicker_flags CDATA #IMPLIED > -->

=== 0x90v1/BlurRebuilt/code/tools/c_sharp/applications/executer/test_data/FarmTemplate.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE root SYSTEM "Executer.dtd" >

<root version = "1.1">

	<config	farm_temp_folder = ".\temp" />

	<servers>
		<server_definition name = "Local farm"				tcp_port = "1234" udp_port = "1234" local_name = "Local test farm"	location = "local" startup_command = "C:\dev\tools\xFarm.exe -p 1234 Dummy" kill_on_exit = "true"/>
		<server_definition name = "Pumpkin Server"		tcp_port = "4321" udp_port = "4321" local_name = "Pumpkin"					location = "unknown"/>
		<server_definition name = "LittlePeterH Server"		tcp_port = "4322" udp_port = "4322" local_name = "LittleH"					location = "unknown"/>
<!--		<server_definition name = "Local farm unknown location"	tcp_port = "125" udp_port = "1235" local_name = "remote"	location = "unknown"/> -->
	</servers>

	<actions>
		<action	name = "copy_xbox"
					command_line = "c:\testapp.exe"
					working_directory = "Z:\Tools\Ravin\Converters\"
					arguments = '"%args_file%" "%server%"'
					include_child_data = "false"
					include_parent_data = "false"
		>

			<server_list>
				<server local_name = "immediate" />
				<server local_name = "Pumpkin" />
			</server_list>
		</action>

		<action	name = "test_task"
			command_line = "c:\TestTask.exe"
			working_directory = "c:\"
			arguments = '"%args_file%" "%server%" "%source_machine%"'
			include_child_data = "false"
			include_parent_data = "false"
		>

			<server_list>
				<server local_name = "immediate" />
				<server local_name = "Pumpkin" />
				<server local_name = "Local test farm" />
				<server local_name = "LittleH" />
			</server_list>
		</action>

		<!--	command_line = "c:\TestTask.exe" command_line = "c:\testapp.exe"-->
		<action	name = "export"
					command_line = "c:\logs4u.exe"
						working_directory = "Z:\Tools\Ravin\Converters\"
						arguments = '"%args_file%" "%server%" "%XEDK%"'
						include_child_data = "true"
						include_parent_data = "false"
		>

			<server_list>
				<server local_name = "immediate" />
				<server local_name = "Local test farm" />
				<server local_name = "LittleH" />
			</server_list>

		</action>

		<action	name = "dummy_task_1"
					command_line = "c:\testapp.exe"
					working_directory = "Z:\Tools\Ravin\Converters\"
					arguments = '"%args_file%" "%server%"'
					include_child_data = "true"
					include_parent_data = "false"
		>

			<server_list>
				<server local_name = "immediate" />
			</server_list>

		</action>

		<action	name = "Test feedback"
			command_line = "c:\logs4u.exe"
			working_directory = "Z:\Tools\Ravin\Converters\"
			arguments = '"%args_file%" "%server%"'
			include_child_data = "false"
			include_parent_data = "false"
		>

			<server_list>
				<server local_name = "Local test farm" />
				<server local_name = "Pumpkin" />
			</server_list>
		</action>
		
	</actions>

	<processes>
		<process name = "Copy to xbox" local_name = "copy xbox"/>
		<process name = "Export" local_name = "export"/>
		<process name = "Full export" local_name = "full export"/>
	</processes>

	<!--<tree_icon_folder name = "Z:\tools\ravin\executer\media\treeicons" />-->

	<types>
		<type name ="root_node" icon1="iconProjectA.bmp" icon2="iconProjectB.bmp">
			<inheritable_types>
				<inheritable_type name ="Folder"/>
			</inheritable_types>

			<sub_menu_template>
				<menu_system>
					<container name = "job1" display_name = "Job 1" type = "basic">
					</container>
				</menu_system>
			</sub_menu_template>
		</type>

		<type name = "Folder" icon1="iconFolderA.bmp" icon2="iconFolderB.bmp">
			<task_list>
				<task name = "Export"					display_name = "Export then copy"	action_name = "export"			process_recursively = "ask"/>
				<task name = "Copy to Xbox"		display_name = "Copy to XBox"			action_name = "copy_xbox"			process_recursively = "no"/>
			</task_list>

			<inheritable_types>
				<inheritable_type name ="Folder"/>
				<inheritable_type name ="Job1"/>
				<inheritable_type name ="Job2"/>
				<inheritable_type name ="Job3"/>
				<inheritable_type name ="Level"/>
			</inheritable_types>

			<sub_menu_template>
			</sub_menu_template>
		</type>

		<type name ="Job1" icon1="iconLevelA.bmp" icon2="iconLevelB.bmp">
			<task_list>
				<task name = "Export" display_name = "Export" action_name = "test_task" process_recursively = "ask"/>
				<task name = "Test feedback" display_name = "Test feedback" action_name = "Test feedback" process_recursively = "ask"/>

			</task_list>
			<inheritable_types>
			</inheritable_types>

			<sub_menu_template>
				<menu_system>
					<container name = "job1" display_name = "Job 1" type = "basic">
						<container name ="action_button" display_name ="Action_button" type ="action_button" default="" pre_format ="cr;" />
						<container name ="bitmap" type ="bitmap" display_name ="Bitmap"  bitmap ="C:\Users\Keith\Desktop\tools\c_sharp\applications\executer\icons\Executer_icon_64.bmp" pre_format ="cr;" />
						<container name ="bool" type ="bool" display_name ="Bool" default ="" pre_format ="cr;" />
						<container name ="colour" type ="colour" display_name ="Colour" default ="" pre_format ="cr;" />
						<container name ="dropdown" type ="dropdown" display_name ="Dropdown" default ="" pre_format ="cr;" />
						<container name ="enum" type ="enum" display_name ="Enum" default ="" pre_format ="cr;" />
						<container name ="filename" type ="filename" display_name ="Filename" default ="" pre_format ="cr;" />
						<container name ="folder" type ="folder" display_name ="Folder" default ="" pre_format ="cr;" />
						<container name ="network_filename" type ="network_filename" display_name ="Network_filename" default ="" pre_format ="cr;" />
						<container name ="label" type ="label" display_name ="Label" default ="" pre_format ="cr;" />
						<container name ="int" type ="int" display_name ="Int" default ="" pre_format ="cr;" />
						<container name ="float" type ="float" display_name ="Float" default ="" pre_format ="cr;" />
						<container name ="progress_bar" type ="progress_bar" display_name ="Progress_bar" default ="" pre_format ="cr;" />
						<container name ="radio_button" type ="radio_button" display_name ="Radio_button" default ="" pre_format ="cr;" />
						<container name ="string" type ="string" display_name ="String" default ="" pre_format ="cr;" />
						<container name ="text" type ="text" display_name ="Text" default ="" pre_format ="cr;" />
						<container name ="tree" type ="tree" display_name ="Tree" default ="" pre_format ="cr;" />
						<container name ="webpage" type ="webpage" display_name ="Webpage" default ="http://www.bbc.co.uk" pre_format ="cr;" />
						<container name ="custom_list" type ="custom_list" display_name ="Custom_list" default ="" pre_format ="cr;" />





						<container name="image1" display_name="image1" type="bitmap" bitmap = "Z:\tools\ravin\executer\media\ToolPcl.bmp" default="" />
						<container name = "input" display_name = "Input" type = "basic" pre_format ="cr;">
							<container name = "level_filename" display_name="Filename" type ="filename" filepicker_filter = "*.lvl" filepicker_share_name = "alienbrainWork"  force_local_network_path = "true" force_file_exists = "true" default="" pre_format ="cr;"/>
						</container>
						<container name = "output" display_name = "Output" type = "basic" pre_format ="cr;">
							<container name = "level_filename" display_name="Filename" type ="filename" filepicker_filter = "*.lvl" filepicker_share_name = "alienbrainWork"  force_local_network_path = "true" force_path_exists = "true" default="" pre_format ="cr;"/>
						</container>

					</container>
				</menu_system>
			</sub_menu_template>
		</type>

		<type name ="Job2" icon1="iconLevelA.bmp" icon2="iconLevelB.bmp">
			<task_list>
				<task name = "Export" display_name = "Export" action_name = "export" process_recursively = "ask" farm_comment = "Processing %object_name% output file is %level_filename%"/>
			</task_list>
			<inheritable_types>
			</inheritable_types>

			<sub_menu_template>
				<menu_system>
					<container name = "job2" display_name = "Job 2" type = "basic">
						<container name="image1" display_name="image1" type="bitmap" bitmap = "Z:\tools\ravin\executer\media\ToolPcl.bmp" default="" />
						<container name = "level_filename" display_name="Filename" type ="filename" filepicker_filter = "*.lvl" filepicker_share_name = "alienbrainWork"  force_local_network_path = "true" force_file_exists = "true" default="" pre_format ="cr;"/>
					</container>
				</menu_system>
			</sub_menu_template>
		</type>

		<type name ="Job3" icon1="iconLevelA.bmp" icon2="iconLevelB.bmp">

			<inheritable_types>
			</inheritable_types>

			<sub_menu_template>
				<menu_system>
					<container name = "job3" display_name = "Job 3" type = "basic">
						<container name="image1" display_name="image1" type="bitmap" bitmap = "Z:\tools\ravin\executer\media\ToolPcl.bmp" default="" />
					</container>
				</menu_system>
			</sub_menu_template>
		</type>

		<type name ="Level" icon1="iconLevelA.bmp" icon2="iconLevelB.bmp">

			<task_list>
				<task name = "Export"					display_name = "Export"					action_name = "export"				process_recursively = "ask"/>
				<task name = "Copy to Xbox"		display_name = "Copy to XBox"		action_name = "copy_xbox"			process_recursively = "no"/>
			</task_list>

			<inheritable_types>
			</inheritable_types>

			<sub_menu_template>
				<menu_system>
					<enums>
						<enum name="Method">
							"Lpvs sample"
							"Cubic"
							"Plane"
						</enum>
					</enums>

					<container name = "level" display_name = "Level" type = "basic">

						<container name="image1" display_name="image1" type="bitmap" bitmap = "Z:\tools\ravin\executer\media\ToolPcl.bmp" default="" />

						<container name = "input" display_name = "Input" type = "basic" pre_format ="cr;">
